## Stupid line
language: java
sudo: false
script: mvn clean package
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ls -R
deploy:
deploy:
  provider: releases
  api_key: "aefddb9f5377f4da9360741d4b308d16b345bd3a"
  file: "SchlaubiBot-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
   tags: false
   all_branches: true
    
